# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.nick/":
    type: upstream
    upstream: "app:http"

"https://nick/":
    type: redirect
    to: "https://www.nick/"
